version: '3'
services:
  app:
    build: .
    ports:
      - "80:80"
    networks:
      - app-net
  db:
    image: "postgres:14"
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net
volumes:
  pgdata:
networks:
  app-net:
