openapi: 3.0.0

info:
  version: '1.0'
  title: 'dei-acolhimento APP'
  description: 'Web Resources Specification for dei-acolhimento'

servers:
- url: https://powerful-falls-60752.herokuapp.com
  description: Production server

externalDocs:
  url: https://git.fe.up.pt/alexandre.valle/dei-acolhimento/-/wikis/home
  description: Project Documentation

tags:
  - name: 'M01: Authentication'
  - name: 'M02: Static Pages'
  - name: 'M03: Topics'
  - name: 'M04: Questions'
  - name: 'M05: Administration'

paths:

  # M01: Authentication

  /login:

    get:
      operationId: R101
      summary: 'R101: Login Form'
      description: 'Provides the login form. ACCESS: VIS'
      tags:
        - 'M01: Authentication'

      responses:
        '200':
          description: 'Ok'

    post:
      operationId: R102
      summary: 'R102: Login Action'
      description: 'Processes login form submission. ACCESS: VIS'
      tags:
        - 'M01: Authentication'

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password

      responses:
        '302':
          description: 'Redirect back to home page after processing the login credentials'
          headers:
            location:
              schema:
                type: string

  /logout:

    post:
      operationId: R103
      summary: 'R103: Logout Action'
      description: 'Logout the current authenticated user. ACCESS: USR, ADM'
      tags:
        - 'M01: Authentication'

      responses:
        '302':
         description: 'Redirect after processing logout.'
         headers:
           Location:
             schema:
               type: string

  /register:

    get:
      operationId: R104
      summary: 'R104: Register Form'
      description: 'Provides the registration form. ACCESS: VIS'
      tags:
        - 'M01: Authentication'

      responses:
        '200':
         description: 'Ok'   
    
    post:
      operationId: R105
      summary: 'R105: Register Action'
      description: 'Processes registration form submission. ACCESS: VIS'
      tags:
        - 'M01: Authentication'

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - name
                - email
                - password

      responses:
        '302':
          description: 'Redirect after processing the new user information.'
          headers:
            location:
              schema:
                type: string

  /recoverAccount:

    get:
      operationId: R106
      summary: 'R106: Recover Account Page'
      description: 'Shows recover account page. ACCESS: VIS'
      tags:
        - 'M01: Authentication'

      responses:
        '200':
          description: 'Ok'

  /recoverAccount/sendEmail: 

    post:
      operationId: R107
      summary: 'R107: Recover Account'
      description: 'Sends an email for account recovery. ACCESS: VIS'
      tags:
        - 'M01: Authentication'

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
                - email

      responses:
        '302':
          description: 'Redirect after sending email.'
          headers:
            location:
              schema:
                type: string

  /reset-password:

      get:
        operationId: R108
        summary: 'R108: Reset Password Page'
        description: 'Shows reset password page. ACCESS: USR, ADM'
        tags:
          - 'M01: Authentication'

        responses:
          '200':
            description: 'Ok'

  /reset-password/{token}:

    post:
      operationId: R109
      summary: 'R109: Reset Password'
      description: 'Resets the current user password. ACCESS: USR, ADM'
      tags:
        - 'M01: Authentication'

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password

      responses:
        '302':
          description: 'Redirect after reseting the password'
          headers:
            location:
              schema:
                type: string


  # M02: Static Pages

  /contatos:

    get:
      operationId: R201
      summary: 'R201: Contacts Page'
      description: 'Shows contacts page. ACCESS: VIS'
      tags:
        - 'M02: Static Pages'
      responses:
        '200':
          description: 'Ok.'


  # M03: Topics

  /topic:

    get:
      operationId: R301
      summary: 'R301: Topic Page'
      description: 'Shows default topic page. ACCESS: VIS' 
      tags:
        - 'M03: Topics'
      responses:
        '200':
          description: 'Ok'

  /topic/{id}:

    get:
      operationId: R302
      summary: 'R302: Specific Topic Page'
      description: 'Shows a specific topic page based on id. ACCESS: VIS'
      tags:
        - 'M03: Topics'
      responses:
        '200':
          description: 'Ok'


  # M04: Questions

  /questions/{id}:

    get:
      operationId: R401
      summary: 'R401: Specific Question Page'
      description: 'Shows a specific question based on id. ACCESS: VIS'
      tags:
        - 'M04: Questions'
      responses:
        '200':
          description: 'Ok'

    post:
      operationId: R402
      summary: 'R402: Submit Answer'
      description: 'Submits the answer to the question. ACCESS: USR, ADM'
      tags:
        - 'M04: Questions'

      responses:
        '302':
          description: 'Redirect after submiting an answer'
          headers:
            location:
              schema:
                type: string

  /quiz/{id}:

    get:
      operationId: R403
      summary: 'R403: Check completed topic.'
      description: 'Redirects to home if quiz completed, otherwise redirects to the topic with id {id}'
      tags:
        - 'M04: Questions'
      responses:
        '200':
          description: 'Ok'


  # M05: Administration

  /admin:

    get:
      operationId: R501
      summary: 'R501: Main Panel.'
      description: 'Shows main panel'
      tags:
        - 'M05: Administration'
      responses:
        '200':
          description: 'Ok'

  /admin/{category}:

    get:
      operationId: R502
      summary: 'R502: Specific Category Panel.'
      description: 'Shows a specific category panel'
      tags:
        - 'M05: Administration'
      responses:
        '200':
          description: 'Ok'

  /admin/topics/{topic}:

    post:
      operationId: R503
      summary: 'R503: Change Topic Active/Disabled'
      description: 'Changes the active status on a specific topic. ACCESS: ADM'
      tags:
        - 'M05: Administration'

      responses:
        '302':
          description: 'Processes the change'
          headers:
            location:
              schema:
                type: string

  /admin/topics/{topic}/up:
    
    post:
      operationId: R504
      summary: 'R504: Change Topic Order one place up'
      description: 'Changes the order on a specific topic one place up. ACCESS: ADM'
      tags:
        - 'M05: Administration'

      responses:
        '302':
          description: 'Processes the change'
          headers:
            location:
              schema:
                type: string

  /admin/topics/{topic}/down:
    
    post:
      operationId: R505
      summary: 'R505: Change Topic Order one place down'
      description: 'Changes the order on a specific topic one place down. ACCESS: ADM'
      tags:
        - 'M05: Administration'

      responses:
        '302':
          description: 'Processes the change'
          headers:
            location:
              schema:
                type: string

  /admin/topics/{topic}/edit:

    post:
      operationId: R506
      summary: 'R506: Edit Topic'
      description: 'Edit the topic. ACCESS: ADM'
      tags:
        - 'M05: Administration'

      responses:
        '302':
          description: 'Processes the change'
          headers:
            location:
              schema:
                type: string

  /admin/topic/delete:

    post:
      operationId: R506
      summary: 'R506: Delete Topic'
      description: 'Deletes a topic. ACCESS: ADM'
      tags:
        - 'M05: Administration'

      responses:
        '302':
          description: 'Processes the change'
          headers:
            location:
              schema:
                type: string

  /admin/topics/create:

    get:
      operationId: R507
      summary: 'R507: Topic Creation Page.'
      description: 'Shows topic creation page'
      tags:
        - 'M05: Administration'
      responses:
        '200':
          description: 'Ok'

  /admin/topics/:

    post:
      operationId: R508
      summary: 'R508: Creates Topic'
      description: 'Creates a topic. ACCESS: ADM'
      tags:
        - 'M05: Administration'

      responses:
        '302':
          description: 'Processes the topic creation'
          headers:
            location:
              schema:
                type: string

  /admin/{topic}/questions:

    get:
      operationId: R509
      summary: 'R509: Questions of Topic Page.'
      description: 'Shows questions of a specific topic page'
      tags:
        - 'M05: Administration'
      responses:
        '200':
          description: 'Ok'

  /admin/topic/{topic}:

    get:
      operationId: R510
      summary: 'R510: Topic Details Page.'
      description: 'Shows a specific topic details page'
      tags:
        - 'M05: Administration'
      responses:
        '200':
          description: 'Ok'

  /admin/question/{question}:

    get:
      operationId: R511
      summary: 'R511: Question Details Page.'
      description: 'Shows a specific question details page'
      tags:
        - 'M05: Administration'
      responses:
        '200':
          description: 'Ok'

  /admin/questions/create:

    get:
      operationId: R512
      summary: 'R512: Question Creation Page.'
      description: 'Shows question creation page'
      tags:
        - 'M05: Administration'
      responses:
        '200':
          description: 'Ok'

    post:
      operationId: R513
      summary: 'R513: Creates Question'
      description: 'Creates a question. ACCESS: ADM'
      tags:
        - 'M05: Administration'

      responses:
        '302':
          description: 'Processes the question creation'
          headers:
            location:
              schema:
                type: string

  /admin/questions/{question}/up:

    post:
      operationId: R514
      summary: 'R514: Change Question Order one place up'
      description: 'Changes the order on a specific question one place up. ACCESS: ADM'
      tags:
        - 'M05: Administration'

      responses:
        '302':
          description: 'Processes the change'
          headers:
            location:
              schema:
                type: string

  /admin/questions/{question}/down:

    post:
      operationId: R515
      summary: 'R515: Change Question Order one place down'
      description: 'Changes the order on a specific question one place down. ACCESS: ADM'
      tags:
        - 'M05: Administration'

      responses:
        '302':
          description: 'Processes the change'
          headers:
            location:
              schema:
                type: string

  /admin/questions/{question}/active:

    post:
      operationId: R516
      summary: 'R516: Change Question Active/Disabled'
      description: 'Changes the active status on a specific question. ACCESS: ADM'
      tags:
        - 'M05: Administration'

      responses:
        '302':
          description: 'Processes the change'
          headers:
            location:
              schema:
                type: string

  /admin/questions/delete:

    post:
      operationId: R517
      summary: 'R517: Delete Question'
      description: 'Deletes a question. ACCESS: ADM'
      tags:
        - 'M05: Administration'

      responses:
        '302':
          description: 'Processes the change'
          headers:
            location:
              schema:
                type: string

  /admin/users/promote:

    post:
      operationId: R518
      summary: 'R518: Promote User'
      description: 'Promotes a user. ACCESS: ADM'
      tags:
        - 'M05: Administration'

      responses:
        '302':
          description: 'Processes the change'
          headers:
            location:
              schema:
                type: string

  /admin/users/delete: 
  
     post:
      operationId: R519
      summary: 'R519: Delete User'
      description: 'Deletes a user. ACCESS: ADM'
      tags:
        - 'M05: Administration'

      responses:
        '302':
          description: 'Processes the change'
          headers:
            location:
              schema:
                type: string

  /admin/users/reward/{user}:

    post:
      operationId: R520
      summary: 'R520: Reward User'
      description: 'Rewards a user. ACCESS: ADM'
      tags:
        - 'M05: Administration'

      responses:
        '302':
          description: 'Processes the change'
          headers:
            location:
              schema:
                type: string

  /admin/posts/{post}/up:

    post:
      operationId: R521
      summary: 'R521: Change Post Order one place up'
      description: 'Changes the order on a specific post one place up. ACCESS: ADM'
      tags:
        - 'M05: Administration'

      responses:
        '302':
          description: 'Processes the change'
          headers:
            location:
              schema:
                type: string

  /admin/posts/{post}/down:

    post:
      operationId: R522
      summary: 'R522: Change Post Order one place down'
      description: 'Changes the order on a specific post one place down. ACCESS: ADM'
      tags:
        - 'M05: Administration'

      responses:
        '302':
          description: 'Processes the change'
          headers:
            location:
              schema:
                type: string

  /admin/posts/{post}/active:

    post:
      operationId: R523
      summary: 'R523: Change Post Active/Disabled'
      description: 'Changes the active status on a specific post. ACCESS: ADM'
      tags:
        - 'M05: Administration'

      responses:
        '302':
          description: 'Processes the change'
          headers:
            location:
              schema:
                type: string

  /admin/posts/delete:

    post:
      operationId: R524
      summary: 'R524: Delete Post'
      description: 'Deletes a post. ACCESS: ADM'
      tags:
        - 'M05: Administration'

      responses:
        '302':
          description: 'Processes the change'
          headers:
            location:
              schema:
                type: string

  /admin/{topic}/posts:

    get:
      operationId: R525
      summary: 'R525: Show Specific Topic Posts'
      description: 'Shows the posts bounded to a specific topic. ACCESS: ADM'
      tags:
        - 'M05: Administration'
      responses:
        '200':
          description: 'Ok'

  /admin/post/{post}:

    get:
      operationId: R526
      summary: 'R526: Post Details Page.'
      description: 'Shows a specific post details page'
      tags:
        - 'M05: Administration'
      responses:
        '200':
          description: 'Ok'

  /admin/posts/create:

    get:
      operationId: R527
      summary: 'R527: Post Creation Page.'
      description: 'Shows post creation page'
      tags:
        - 'M05: Administration'
      responses:
        '200':
          description: 'Ok'

    post:
      operationId: R528
      summary: 'R528: Creates Post'
      description: 'Creates a Poat. ACCESS: ADM'
      tags:
        - 'M05: Administration'

      responses:
        '302':
          description: 'Processes the post creation'
          headers:
            location:
              schema:
                type: string

  /admin/question/{question}/{answer}/up:

    post:
      operationId: R529
      summary: 'R529: Change Answer Order one place up'
      description: 'Changes the order on a specific answer bounded to a question, one place up. ACCESS: ADM'
      tags:
        - 'M05: Administration'

      responses:
        '302':
          description: 'Processes the change'
          headers:
            location:
              schema:
                type: string

  /admin/question/{question}/{answer}/down:

    post:
      operationId: R530
      summary: 'R530: Change Answer Order one place down'
      description: 'Changes the order on a specific answer bounded to a question, one place down. ACCESS: ADM'
      tags:
        - 'M05: Administration'

      responses:
        '302':
          description: 'Processes the change'
          headers:
            location:
              schema:
                type: string




  /admin/question/{question}/correct/{answer}: 

    post:
      operationId: R531
      summary: 'R531: Set correct Answer'
      description: 'Sets the correct answer bounded to a question. ACCESS: ADM'
      tags:
        - 'M05: Administration'

      responses:
        '302':
          description: 'Processes the change'
          headers:
            location:
              schema:
                type: string


  /admin/question/{question}/answer:

    post:
      operationId: R532
      summary: 'R532: Add Answer'
      description: 'Adds an answer bounded to a question. ACCESS: ADM'
      tags:
        - 'M05: Administration'

      responses:
        '302':
          description: 'Processes the change'
          headers:
            location:
              schema:
                type: string

  /admin/answer/{answer}:

    delete:
      operationId: R533
      summary: 'R533: Delete Answer'
      description: 'Deletes an answer. ACCESS: ADM'
      tags:
        - 'M05: Administration'

      responses:
        '302':
          description: 'Processes the change'
          headers:
            location:
              schema:
                type: string

  /admin/question/{question}/content:

    post:
      operationId: R534
      summary: 'R534: Edit Question'
      description: 'Edit the question content. ACCESS: ADM'
      tags:
        - 'M05: Administration'

      responses:
        '302':
          description: 'Processes the change'
          headers:
            location:
              schema:
                type: string

  /post/{post}:

    post:
      operationId: R506
      summary: 'R506: Edit Post'
      description: 'Edit the post content. ACCESS: ADM'
      tags:
        - 'M05: Administration'

      responses:
        '302':
          description: 'Processes the change'
          headers:
            location:
              schema:
                type: string

